version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
  modules-poc:
    image: modules-poc
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - "SPRING_PROFILES_ACTIVE=development"
      - DEBUG=true
    depends_on:
      - db